#!/usr/bin/env bash
# script to redirect

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'

echo "http {
	server {
		listen 80;
		location /redirect_me {
			return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
		}
	}
}

events { }
" > /etc/nginx/nginx.conf
service nginx start
